# Generated by Django 3.0.6 on 2021-01-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_comparereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparereport',
            name='pilihan_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comparereport',
            name='pilihan_2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
